[profile.default]
solc = "0.8.25"
src = "src"
out = "forge-artifacts"
libs = ["node_modules", "lib", "dependencies"]
remappings = [
    "hardhat/=node_modules/hardhat/",
    "solidity-proxy/=node_modules/solidity-proxy/"
]
test = 'test/foundry'
cache_path  = 'forge-cache'

[dependencies]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
